from typing import List

from pydantic import BaseModel

from core.models import AcceptedUpdate, Book, CandidateUpdate, Chapter, Section


class ChapterAnalysisScore(BaseModel):
    summary: str
    key_concepts: List[str]
    search_queries: List[str]


class JudgeScore(BaseModel):
    relevance: float
    significance: float
    credibility: float
    novelty: float
    pedagogical_fit: float
    final_score: float
    decision: str
    reason: str


class ExtractedEvidence(BaseModel):
    """LLM-generated evidence candidate from a retrieval result.
    Source metadata (url, date, source_type) is added post-hoc from retrieval data,
    NOT generated by the LLM — keeps the schema focused on extraction quality."""
    candidate_title: str
    summary: str
    why_it_matters: str


class SectionMapping(BaseModel):
    """LLM-generated mapping of an update to the best textbook section."""
    mapped_section_id: str
    reason: str


class WriterOutput(BaseModel):
    """Structured writer output — eliminates brittle newline-based text splitting."""
    title: str
    paragraph_1: str
    paragraph_2: str


class DomainEvaluation(BaseModel):
    """LLM-generated evaluation of a web domain's credibility."""
    credibility_score: float
    reason: str
